### ISSUE TITLE
Add a "run not working" message to the page

### ISSUE THREAD

**Issue by snoyberg** [fpco/schoolofhaskell.com#2]
We've gotten a few Disqus comments from people confused about the lack of active code, usually complaining "there's no run button." While this is explained in [the recent blog post](https://www.fpcomplete.com/blog/2016/01/soh-status), obviously not everyone reads the blog before visiting SoH.

Until active code is reenabled, let's add a short message to the top along the lines of "The run button is not currently available, see our [Status of School of Haskell blog post](https://www.fpcomplete.com/blog/2016/01/soh-status)."

Pinging @mgsloan

**Comment by mgsloan** [comment]
Good point.  I've pushed a commit adding this:

![2016-01-11-181110_1101x257_scrot](https://cloud.githubusercontent.com/assets/22570/12252737/b8cc356c-b88e-11e5-8527-c1e366e7597b.png)

**Comment by mgsloan** [comment]
Deployed!
